gf-platformid: use `qemu-img create` instead of reflinks
I spent a few hours yesterday trying to figure out why my Azure images
were failing to boot in the cloud with:

    error: ../../grub-core/fs/fshelp.c:257:file `/grub2/i386-pc/normal.mod' not found.

What it came down to was whether or not we were doing a reflink copy in
`gf-platformid`. (My root filesystem is configured with reflink support,
so `--reflink=auto` would use reflinks.)

I seem to be hitting a kernel regression of some kind where reflinks +
interactions with guestfish cause the `grub2/` directory of the boot
partition to become corrupted:

```
$ guestmount -a tmp/azure.vhd -m /dev/sda1 tmp/mount && ll /srv/rhcos/tmp/mount
ls: cannot access 'grub2': Bad message
total 20
drwxrwxr-x. 2 root root  1024 Nov 19 11:55 efi
d?????????? ? ?    ?        ?            ? grub2
-rw-rw-r--. 1 root root     0 Nov 19 11:56 ignition.firstboot
lrwxrwxrwx. 1 root root     8 Nov 19 11:56 loader -> loader.1
drwxr-xr-x. 3 root root  1024 Nov 19 11:56 loader.1
drwx------. 2 root root 12288 Nov 19 11:55 lost+found
drwxrwxr-x. 3 root root  1024 Nov 19 11:56 ostree
```

In fact, reproducing the cloud failure is easy to do locally too,
because qemu-kvm will happily boot VHDs, so one can just do
`cosa run -d /path/to/vhd`.

I haven't filed a bug report for this yet because I've been trying to
get a more minimal reproducer and bisecting kernel versions without much
success (for one, it doesn't seem to reproduce in VMs).

The previous patch disabled reflinks globally. Though this makes
`gf-platformid` much slower because it has to copy the full qcow2.
Another more lightweight method here is to just create a new qcow2 and
use the source as its backing file. (Not to mention it also makes it
much faster for all the other devs/CI pipelines which *don't* run with
reflinks on).